import type { UseFormRegister, UseFormSetValue } from "react-hook-form";
import type { BrandFormValues } from "../schemas/branding.schema";
import type { BrandCategory } from "./BrandCategoryGrid";
import { ColorField } from "./ColorField";
import { GradientEditor } from "./GradientEditor";
import { LogoEditor } from "./LogoEditor";
import { RichTextEditor } from "./RichTextEditor";

const palette = [["accent","Acento"],["background","Fondo"],["surface","Paneles"],["foreground","Texto principal"],["muted","Texto secundario"],["line","Separadores"],["topbarText","Texto barra superior"]] as const;
const buttonColors = [["primaryDark","Principal hover"],["buttonText","Texto principal"],["secondary","Secundario"],["secondaryText","Texto secundario"],["success","Éxito"],["warning","Advertencia"],["danger","Peligro"]] as const;

export function BrandCategoryFields({ category, values, register, setValue }: { category: BrandCategory; values: BrandFormValues; register: UseFormRegister<BrandFormValues>; setValue: UseFormSetValue<BrandFormValues> }) {
  if (category === "text") return <><RichTextEditor kind="title" values={values} register={register} setValue={setValue}/><RichTextEditor kind="subtitle" values={values} register={register} setValue={setValue}/></>;
  if (category === "colors") return <fieldset className="field field-wide"><legend>Paleta visual</legend><div className="form">{palette.map(([name,label]) => <ColorField key={name} name={name} label={label} register={register}/>)}</div></fieldset>;
  if (category === "buttons") return <><fieldset className="field field-wide"><legend>Colores de botones y estados</legend><div className="form"><ColorField name="primary" label="Principal" register={register}/>{buttonColors.map(([name,label]) => <ColorField key={name} name={name} label={label} register={register}/>)}</div></fieldset><GradientEditor kind="button" register={register}/></>;
  if (category === "typography") return <fieldset className="field field-wide"><legend>Tipografía y disposición</legend><div className="form"><label className="field"><span>Tipografía</span><select {...register("fontFamily")}><option value="Segoe UI, Arial, Helvetica, sans-serif">Segoe UI</option><option value="Arial, Helvetica, sans-serif">Arial</option><option value="Tahoma, Arial, sans-serif">Tahoma</option><option value="Georgia, 'Times New Roman', serif">Georgia</option></select></label><label className="field"><span>Alineación</span><select {...register("headerTextAlign")}><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select></label><label className="field"><span>Ubicación vertical</span><select {...register("headerTextPosition")}><option value="top">Arriba</option><option value="middle">Centro</option><option value="bottom">Abajo</option></select></label></div></fieldset>;
  if (category === "header") return <GradientEditor kind="header" register={register}/>;
  if (category === "menu") return <><fieldset className="field field-wide"><legend>Presentación del menú</legend><div className="form"><label className="field"><span>Modo</span><select {...register("menuMode")}><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label><label className="check-field"><input type="checkbox" {...register("menuCollapsed")}/>Menú plegado</label><label className="check-field"><input type="checkbox" {...register("mobileMenuCollapsed")}/>Menú móvil plegado</label><label className="field field-wide"><span>Orden de rutas</span><textarea rows={4} {...register("menuOrder")}/><small>Separe las rutas por comas para definir su orden.</small></label></div></fieldset><GradientEditor kind="menu" register={register}/></>;
  if (category === "agenda") return <fieldset className="field field-wide"><legend>Parámetros de agenda</legend><div className="form"><label className="field"><span>Inicio jornada</span><input type="time" {...register("workdayStartTime")}/></label><label className="field"><span>Fin jornada</span><input type="time" {...register("workdayEndTime")}/></label><label className="field"><span>Días para replanificar</span><input type="number" min="0" max="365" {...register("replanningWindowDays", { valueAsNumber: true })}/></label></div></fieldset>;
  if (category === "forms") return <fieldset className="field field-wide"><legend>Campos administrados</legend><label className="check-field"><input type="checkbox" {...register("showProductIdField")}/>Mostrar Id de producto al crear o editar productos</label></fieldset>;
  if (category === "images") return <LogoEditor register={register} setValue={setValue}/>;
  return <LoginFields register={register}/>;
}

function LoginFields({ register }: { register: UseFormRegister<BrandFormValues> }) {
  return <><ActivationPeriod title="Crear requerimiento sin login" enabled="showPublicRequirementForm" from="publicRequirementFormActiveFrom" until="publicRequirementFormActiveUntil" register={register}/><ActivationPeriod title="Formulario público completo" enabled="showPublicRequirementFullPage" from="publicRequirementFullPageActiveFrom" until="publicRequirementFullPageActiveUntil" register={register}/><ActivationPeriod title="Robot Puma" enabled="showLoginChatbot" from="loginChatbotActiveFrom" until="loginChatbotActiveUntil" register={register}/><fieldset className="field field-wide"><legend>Otras opciones</legend><div className="form"><label className="check-field"><input type="checkbox" {...register("showDemoCredentials")}/>Mostrar credenciales de prueba</label><label className="check-field"><input type="checkbox" {...register("showOffice365Login")}/>Mostrar ingreso Office 365</label></div></fieldset></>;
}

type DateName = "publicRequirementFormActiveFrom" | "publicRequirementFormActiveUntil" | "publicRequirementFullPageActiveFrom" | "publicRequirementFullPageActiveUntil" | "loginChatbotActiveFrom" | "loginChatbotActiveUntil";
type FlagName = "showPublicRequirementForm" | "showPublicRequirementFullPage" | "showLoginChatbot";
function ActivationPeriod({ title, enabled, from, until, register }: { title: string; enabled: FlagName; from: DateName; until: DateName; register: UseFormRegister<BrandFormValues> }) {
  return <fieldset className="field field-wide"><legend>{title}</legend><div className="form"><label className="check-field field-wide"><input type="checkbox" {...register(enabled)}/>Mostrar opción</label><label className="field"><span>Activo desde</span><input type="datetime-local" {...register(from)}/></label><label className="field"><span>Activo hasta</span><input type="datetime-local" {...register(until)}/></label></div></fieldset>;
}
