import { Bold, Italic, Underline } from "lucide-react";
import type { UseFormRegister, UseFormSetValue } from "react-hook-form";
import type { BrandFormValues } from "../schemas/branding.schema";
import { ColorField } from "./ColorField";

type TextKind = "title" | "subtitle";

export function RichTextEditor({ kind, values, register, setValue }: { kind: TextKind; values: BrandFormValues; register: UseFormRegister<BrandFormValues>; setValue: UseFormSetValue<BrandFormValues> }) {
  const title = kind === "title";
  const fields = title ? { content: "title", visible: "showHeaderTitle", size: "headerTitleSize", weight: "headerTitleWeight", italic: "headerTitleItalic", underline: "headerTitleUnderline", color: "headerTitleColor", label: "Título", max: 120 } as const : { content: "subtitle", visible: "showHeaderSubtitle", size: "headerSubtitleSize", weight: "headerSubtitleWeight", italic: "headerSubtitleItalic", underline: "headerSubtitleUnderline", color: "headerSubtitleColor", label: "Subtítulo", max: 180 } as const;
  const bold = values[fields.weight] === "700";
  return <fieldset className="field field-wide"><legend>{fields.label}</legend><div className="form"><label className="field field-wide"><span>Contenido del {fields.label.toLowerCase()}</span><input maxLength={fields.max} {...register(fields.content)}/></label><label className="check-field"><input type="checkbox" {...register(fields.visible)}/>Mostrar en la cabecera</label><label className="field"><span>Tamaño</span><input type="number" min={title ? 14 : 10} max={title ? 32 : 24} {...register(fields.size, { valueAsNumber: true })}/></label><ColorField label="Color" name={fields.color} register={register}/><div className="field"><span>Formato enriquecido</span><div className="rich-text-toolbar" role="toolbar" aria-label={`Formato del ${fields.label.toLowerCase()}`}><button className={bold ? "icon-button active" : "icon-button"} type="button" aria-label={`Negrita del ${fields.label.toLowerCase()}`} aria-pressed={bold} onClick={() => setValue(fields.weight, bold ? "400" : "700", { shouldDirty: true, shouldValidate: true })}><Bold aria-hidden="true" size={16}/></button><button className={values[fields.italic] ? "icon-button active" : "icon-button"} type="button" aria-label={`Cursiva del ${fields.label.toLowerCase()}`} aria-pressed={values[fields.italic]} onClick={() => setValue(fields.italic, !values[fields.italic], { shouldDirty: true })}><Italic aria-hidden="true" size={16}/></button><button className={values[fields.underline] ? "icon-button active" : "icon-button"} type="button" aria-label={`Subrayado del ${fields.label.toLowerCase()}`} aria-pressed={values[fields.underline]} onClick={() => setValue(fields.underline, !values[fields.underline], { shouldDirty: true })}><Underline aria-hidden="true" size={16}/></button></div></div></div></fieldset>;
}
