"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getSession, showToast } from "../../../app/lib";
import { getAgendaWorkspace } from "../../agenda/services/agenda.service";
import { buildWorkdayRange, filterAgendaActivities, filterAgendaTechnicians, mergeAgendaReservations } from "../../agenda/utils/agenda.utils";
import type { AgendaItem, Technician } from "../../agenda/models/agenda.models";
import type { CalendarMode, WeekScope } from "../models/calendar.models";
import { buildDayHours, filterCalendarItems, isInPeriod, moveCalendarPeriod, periodDays, startOfDay, uniqueOptions } from "../utils/calendar.utils";

export function useAgendaCalendar() {
  const [data, setData] = useState<Awaited<ReturnType<typeof getAgendaWorkspace>> | null>(null);
  const [mode, setMode] = useState<CalendarMode>("week"); const [weekScope, setWeekScope] = useState<WeekScope>("workdays"); const [cursorDate, setCursorDate] = useState(() => startOfDay(new Date()));
  const [selectedTechnician, setSelectedTechnician] = useState(""); const [selectedCampus, setSelectedCampus] = useState(""); const [selectedStatus, setSelectedStatus] = useState(""); const [search, setSearch] = useState(""); const [selectedItem, setSelectedItem] = useState<AgendaItem | null>(null);
  const [isLoading, setIsLoading] = useState(true); const [isRefreshing, setIsRefreshing] = useState(false); const [loadError, setLoadError] = useState("");
  const load = useCallback((initial = false) => { const request = (async () => { initial ? setIsLoading(true) : setIsRefreshing(true); try { const next = await getAgendaWorkspace(); const session = getSession(); const technicians = filterAgendaTechnicians(next.technicians, session); const fallback: Technician[] = session ? [{ id: session.user.id, name: session.user.name, email: session.user.email, roles: session.user.roles, isActive: true }] : []; const visibleTechnicians = technicians.length ? technicians : fallback; setData({ ...next, technicians: visibleTechnicians, activities: filterAgendaActivities(next.activities, session) }); const canSeeAll = Boolean(session?.user.roles.some((role) => ["Administrador", "Coordinador"].includes(role))); setSelectedTechnician((value) => value || (canSeeAll ? "" : visibleTechnicians[0]?.email ?? "")); setLoadError(""); } catch (error) { const feedback = error instanceof Error ? error.message : "No se pudo cargar el calendario técnico."; setLoadError(feedback); showToast(feedback, "error"); if (!getSession()) window.location.assign("/login"); throw error; } finally { setIsLoading(false); setIsRefreshing(false); } })(); return request; }, []);
  useEffect(() => { void load(true).catch(() => undefined); }, [load]);
  const computed = useMemo(() => { if (!data) return { period: [], items: [], hours: [], activityById: new Map(), requirementById: new Map(), campuses: [], statuses: [] }; const activityById = new Map(data.activities.map((item) => [item.id, item])); const requirementById = new Map(data.requirements.map((item) => [item.id, item])); const range = buildWorkdayRange(data.workdayStartTime, data.workdayEndTime); const agenda = mergeAgendaReservations(data.items, data.activities, requirementById, data.technicians, range); const visible = filterCalendarItems(agenda, selectedTechnician, selectedCampus, selectedStatus, search, activityById, requirementById); const period = periodDays(cursorDate, mode, weekScope === "full"); return { period, items: visible.filter((item) => isInPeriod(item, period)), hours: buildDayHours(range), activityById, requirementById, campuses: uniqueOptions(data.requirements.map((item) => item.campus)), statuses: uniqueOptions(data.activities.map((item) => item.status)) }; }, [cursorDate, data, mode, search, selectedCampus, selectedStatus, selectedTechnician, weekScope]);
  return { mode, setMode, weekScope, setWeekScope, cursorDate, setCursorDate, movePeriod: (direction: number) => setCursorDate((value) => moveCalendarPeriod(value, mode, direction)), today: () => setCursorDate(startOfDay(new Date())), selectedTechnician, setSelectedTechnician, selectedCampus, setSelectedCampus, selectedStatus, setSelectedStatus, search, setSearch, selectedItem, setSelectedItem, technicians: data?.technicians ?? [], workdayStartTime: data?.workdayStartTime ?? "08:00", workdayEndTime: data?.workdayEndTime ?? "17:00", replanningWindowDays: data?.replanningWindowDays ?? 0, isLoading, isRefreshing, loadError, refresh: () => load(), ...computed };
}
