import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { getSession, showToast } from "../../../app/lib";
import { getAgendaWorkspace } from "../../agenda/services/agenda.service";
import { useAgendaCalendar } from "./useAgendaCalendar";
vi.mock("../../../app/lib", () => ({ getSession: vi.fn(), showToast: vi.fn() }));
vi.mock("../../agenda/services/agenda.service", () => ({ getAgendaWorkspace: vi.fn() }));
const sessionMock = vi.mocked(getSession), workspaceMock = vi.mocked(getAgendaWorkspace);
beforeEach(() => { vi.clearAllMocks(); sessionMock.mockReturnValue(session(["Administrador"])); workspaceMock.mockResolvedValue(workspace()); });
describe("useAgendaCalendar", () => {
  it("carga datos compartidos y permite filtros", async () => { const { result, unmount } = renderHook(() => useAgendaCalendar()); await waitFor(() => expect(result.current.isLoading).toBe(false)); expect(result.current.technicians).toHaveLength(2); act(() => { result.current.setSelectedTechnician("tech@example.com"); result.current.setSelectedCampus("Centro"); result.current.setSelectedStatus("InProgress"); result.current.setSearch("campaña"); }); expect(result.current.items).toHaveLength(1); unmount(); });
  it("navega vistas, periodos y fin de semana", async () => { const { result, unmount } = renderHook(() => useAgendaCalendar()); await waitFor(() => expect(result.current.isLoading).toBe(false)); const before = result.current.cursorDate; act(() => { result.current.setMode("day"); result.current.movePeriod(1); }); expect(result.current.cursorDate.getTime()).toBeGreaterThan(before.getTime()); act(() => { result.current.setMode("week"); result.current.setWeekScope("full"); }); expect(result.current.period).toHaveLength(7); act(() => result.current.today()); expect(result.current.cursorDate.getHours()).toBe(0); unmount(); });
  it("restringe técnico para rol operativo", async () => { sessionMock.mockReturnValue(session(["Tecnico"])); const { result, unmount } = renderHook(() => useAgendaCalendar()); await waitFor(() => expect(result.current.isLoading).toBe(false)); expect(result.current.technicians.map((item) => item.email)).toEqual(["tech@example.com"]); expect(result.current.selectedTechnician).toBe("tech@example.com"); unmount(); });
  it("expone error y permite reintentar", async () => { workspaceMock.mockRejectedValueOnce(new Error("Sin conexión")); const { result, unmount } = renderHook(() => useAgendaCalendar()); await waitFor(() => expect(result.current.loadError).toBe("Sin conexión")); expect(showToast).toHaveBeenCalledWith("Sin conexión", "error"); await act(async () => { await result.current.refresh(); }); expect(result.current.loadError).toBe(""); unmount(); });
});
function session(roles: string[]) { return { accessToken: "t", expiresAt: "x", user: { id: "u", name: "Tech", email: "tech@example.com", roles, screenPermissions: ["agenda-calendar"] } }; }
function workspace() { return { activities: [{ id: "p1", requirementId: "r1", productId: "PROD-1", requirementTypeId: "r", requirementType: "R", strategicObjective: "O", targetAudienceId: "t", targetAudience: "T", productTypeId: "p", productType: "Video", diffusionChannelId: "d", diffusionChannel: "Web", mainKpiId: "k", mainKpi: "K", productResponsible: "tech@example.com", observations: "", status: "InProgress", statusId: "s" }], requirements: [{ id: "r1", code: "R", activityOrEvent: "E", requestedBy: "u", facultyId: "f", faculty: "F", career: "C", campusId: "c", campus: "Centro", place: "P", startDate: "2026-01-01", endDate: "2026-12-31", eventObjective: "O", eventFormatId: "e", eventFormat: "E", requestDate: "x", status: "InProgress", statusId: "s" }], technicians: [{ id: "t", name: "Tech", email: "tech@example.com", roles: ["Tecnico"], isActive: true }, { id: "o", name: "Otro", email: "otro@example.com", roles: ["Tecnico"], isActive: true }], items: [{ id: "a1", activityId: "p1", requirementId: "r1", productId: "PROD-1", productType: "Video", technicianName: "Tech", technicianEmail: "tech@example.com", startAt: new Date().toISOString(), endAt: new Date(Date.now() + 3_600_000).toISOString(), title: "Campaña", notes: "" }], workdayStartTime: "08:00", workdayEndTime: "17:00", replanningWindowDays: 3 }; }
