services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate --protocol http2 --no-tls-verify --url https://nginx:443
    depends_on:
      - nginx
