services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run apptraficomkt
    volumes:
      - ./deploy/cloudflared:/etc/cloudflared:ro
    depends_on:
      - nginx
