import type { Activity } from "../../../shared/models/api.models";
import type { UsageMetrics } from "../models/metrics.models";
import { buildUsageRows, formatMetricDate } from "../utils/metrics.utils";
import { MetricCard } from "./MetricCard";

export function UsageSection({ usage, activities }: { usage: UsageMetrics | null; activities: Activity[] }) {
  const rows = buildUsageRows(usage, activities);
  return <section className="panel"><h2>Usabilidad de usuarios</h2><div className="metric-grid top-space"><MetricCard label="Usuarios" value={usage?.totalUsers ?? 0} detail="registrados" /><MetricCard label="Activos" value={usage?.activeUsers ?? 0} detail="habilitados" /><MetricCard label="Uso reciente" value={usage?.usersLoggedLast7Days ?? 0} detail="últimos 7 días" /><MetricCard label="Horas sin uso" value={usage?.averageHoursSinceLastLogin ?? 0} detail="promedio desde último login" /></div>{rows.length === 0 ? <div className="empty top-space">Sin actividad reciente de usuarios.</div> : <div className="stack compact-stack top-space">{rows.map(({ user, assigned, approved, inProgress }) => <article className="card compact-card" key={user.email}><div className="card-head"><div className="compact-title"><h3>{user.name}</h3><p>{user.email}</p></div><span className="badge">{user.isActive ? "Activo" : "Inactivo"}</span></div><div className="detail-grid compact-detail-grid"><div className="detail-item"><span>Roles</span><strong>{user.roles}</strong></div><div className="detail-item"><span>Último ingreso</span><strong>{formatMetricDate(user.lastLoginAt)}</strong></div><div className="detail-item"><span>Productos asignados</span><strong>{assigned.length}</strong></div><div className="detail-item"><span>En gestión</span><strong>{inProgress}</strong></div><div className="detail-item"><span>Aprobados</span><strong>{approved}</strong></div></div>{assigned.length > 0 && <div className="nested-detail top-space">{assigned.slice(0, 5).map((activity) => <div className="inline-facts" key={activity.id}><span>{activity.productId}</span><span>{activity.productType}</span><span>{activity.status}</span><span>{activity.productDeliveryDate ?? "Sin entrega"}</span></div>)}</div>}</article>)}</div>}</section>;
}
