import { CalendarDays, Clock, UserRound } from "lucide-react";
import type { AgendaItem } from "../../agenda/models/agenda.models";
import { duration, itemsForDay, shortDate, timeRange } from "../utils/calendar.utils";

export function DayView({ date, items, hours, onOpen }: { date: Date; items: AgendaItem[]; hours: number[]; onOpen: (item: AgendaItem) => void }) { return <div className="day-calendar top-space"><div className="day-calendar-head"><CalendarDays size={18} /><strong>{date.toLocaleDateString("es-EC", { dateStyle: "full" })}</strong></div><div className="day-timeline">{hours.map((hour) => <div className="day-hour-row" key={hour}><span>{String(hour).padStart(2, "0")}:00</span><div>{items.filter((item) => new Date(item.startAt).getHours() === hour).map((item) => <CalendarEvent key={item.id} item={item} onOpen={onOpen} />)}</div></div>)}</div></div>; }
export function WeekView({ days, items, hours, onOpen }: { days: Date[]; items: AgendaItem[]; hours: number[]; onOpen: (item: AgendaItem) => void }) { return <div className={`week-calendar top-space ${days.length === 5 ? "workweek" : ""}`}><div className="week-grid-head empty-cell">Hora</div>{days.map((day) => <div className="week-grid-head" key={day.toISOString()}><strong>{day.toLocaleDateString("es-EC", { weekday: "short" })}</strong><span>{shortDate(day)}</span></div>)}{hours.map((hour) => <div className="week-grid-row" key={hour}><div className="week-time-cell">{String(hour).padStart(2, "0")}:00</div>{days.map((day) => <div className="week-slot-cell" key={`${day.toISOString()}-${hour}`}>{itemsForDay(items, day).filter((item) => new Date(item.startAt).getHours() === hour).map((item) => <CalendarEvent key={item.id} item={item} onOpen={onOpen} />)}</div>)}</div>)}</div>; }
export function MonthView({ cursorDate, days, items, onOpen }: { cursorDate: Date; days: Date[]; items: AgendaItem[]; onOpen: (item: AgendaItem) => void }) { return <div className="month-calendar top-space">{["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"].map((day) => <strong className="month-weekday" key={day}>{day}</strong>)}{days.map((day) => { const values = itemsForDay(items, day); return <section className={`month-day ${day.getMonth() === cursorDate.getMonth() ? "" : "outside-month"}`} key={day.toISOString()}><div className="month-day-number">{day.getDate()}</div><div className="month-events">{values.slice(0, 3).map((item) => <CalendarEvent compact key={item.id} item={item} onOpen={onOpen} />)}{values.length > 3 && <button className="calendar-more" type="button" onClick={() => onOpen(values[3])}>+{values.length - 3} más</button>}</div></section>; })}</div>; }
export function ListView({ items, onOpen }: { items: AgendaItem[]; onOpen: (item: AgendaItem) => void }) { const ordered = [...items].sort((a, b) => new Date(a.startAt).getTime() - new Date(b.startAt).getTime()); return <div className="booking-list top-space">{ordered.map((item) => <button className="booking-list-row" type="button" key={item.id} onClick={() => onOpen(item)}><span>{new Date(item.startAt).toLocaleDateString("es-EC", { weekday: "short", day: "numeric" })}</span><strong>{item.title}</strong><em>{duration(item).toFixed(1)} h · {item.productType}</em><b>Confirmado</b></button>)}{ordered.length === 0 && <div className="calendar-empty">No hay compromisos para el periodo seleccionado.</div>}</div>; }
export function CalendarEvent({ item, compact = false, onOpen }: { item: AgendaItem; compact?: boolean; onOpen: (item: AgendaItem) => void }) { return <button className={`calendar-event ${compact ? "compact" : ""} ${item.id.startsWith("auto-") ? "auto-reserved" : ""}`} type="button" aria-label={`Ver ${item.title}`} onClick={() => onOpen(item)}><strong>{compact ? item.productId : item.title}</strong>{!compact && <span>{item.productId} | {item.productType}</span>}<small><Clock size={12} /> {timeRange(item)}</small>{item.id.startsWith("auto-") && <small>Jornada completa</small>}{!compact && <em><UserRound size={12} /> {item.technicianName}</em>}</button>; }
