import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { CalendarToolbar } from "./CalendarToolbar";
import { DayView, ListView, MonthView, WeekView } from "./CalendarViews";
import { monthGrid, weekDays } from "../utils/calendar.utils";
describe("CalendarToolbar", () => { it("cambia vista y navega", async () => { const user = userEvent.setup(); const onMode = vi.fn(), onMove = vi.fn(); render(<CalendarToolbar mode="week" cursorDate={new Date("2026-01-05")} refreshing={false} onMode={onMode} onDate={vi.fn()} onMove={onMove} onToday={vi.fn()} onRefresh={vi.fn()} />); await user.click(screen.getByRole("button", { name: "Mes" })); expect(onMode).toHaveBeenCalledWith("month"); await user.click(screen.getByRole("button", { name: "Periodo siguiente" })); expect(onMove).toHaveBeenCalledWith(1); }); });
describe("Calendar views", () => { it("renderiza día, semana, mes y lista", async () => { const onOpen = vi.fn(); const date = new Date("2026-01-05T00:00:00"); const value = item(); const { rerender } = render(<DayView date={date} items={[value]} hours={[8]} onOpen={onOpen} />); await userEvent.click(screen.getByRole("button", { name: "Ver Campaña" })); expect(onOpen).toHaveBeenCalledWith(value); rerender(<WeekView days={weekDays(date, false)} items={[value]} hours={[8]} onOpen={onOpen} />); expect(screen.getByText(/lun/i)).toBeInTheDocument(); rerender(<MonthView cursorDate={date} days={monthGrid(date)} items={[value]} onOpen={onOpen} />); expect(screen.getByText("Lun")).toBeInTheDocument(); rerender(<ListView items={[value]} onOpen={onOpen} />); expect(screen.getByText("Confirmado")).toBeInTheDocument(); }); it("presenta lista vacía", () => { render(<ListView items={[]} onOpen={vi.fn()} />); expect(screen.getByText(/No hay compromisos/)).toBeInTheDocument(); }); });
function item() { return { id: "a1", activityId: "p1", requirementId: "r1", productId: "PROD-1", productType: "Video", technicianName: "Tech", technicianEmail: "tech@example.com", startAt: "2026-01-05T08:00:00", endAt: "2026-01-05T10:00:00", title: "Campaña", notes: "" }; }
