tunnel: apptraficomkt
credentials-file: /etc/cloudflared/apptraficomkt.json

ingress:
  - hostname: marketingtrafico.indoamerica.edu.ec
    service: https://nginx:443
    originRequest:
      noTLSVerify: true
  - service: http_status:404
