table _Medidas
	isHidden
	lineageTag: 78ffbd44-2c9f-4ef3-8589-3836eed3a519

	measure 'Total requerimientos' = COUNTROWS ( FactRequerimiento )
		formatString: 0
		lineageTag: 840627bf-9fac-4ec6-b7c9-a21cbe5dc2f6

	measure 'Total productos' = COUNTROWS ( FactProducto )
		formatString: 0
		lineageTag: eb304825-fb9c-4199-8c5f-aa2c6382dfa0

	measure 'Productos aprobados' = CALCULATE ( [Total productos], FactProducto[EsAprobado] = TRUE () )
		formatString: 0
		lineageTag: 1d3f3442-88f1-4dbf-b350-d8de2e71beea

	measure 'Satisfaccion promedio' = AVERAGE ( FactSatisfaccion[SatisfaccionGeneral] )
		formatString: 0.00
		lineageTag: 63dec9cd-e921-4981-a694-e798941a3b56

	measure 'Dias promedio ciclo requerimiento' = DIVIDE ( AVERAGE ( FactRequerimiento[HorasLaborablesCiclo] ), 8 )
		formatString: 0.0
		lineageTag: 11111111-1111-4111-8111-111111111101

	measure 'Dias promedio antiguedad requerimiento' = DIVIDE ( AVERAGE ( FactRequerimiento[HorasLaborablesAntiguedad] ), 8 )
		formatString: 0.0
		lineageTag: 11111111-1111-4111-8111-111111111102

	measure 'Dias promedio anticipacion' = AVERAGE ( FactRequerimiento[DiasAnticipacion] )
		formatString: 0.0
		lineageTag: 11111111-1111-4111-8111-111111111103

	measure 'Dias promedio ejecucion tecnica' = DIVIDE ( AVERAGE ( FactProducto[HorasTecnicasLaborables] ), 8 )
		formatString: 0.0
		lineageTag: 11111111-1111-4111-8111-111111111104

	measure 'Dias promedio aprobacion' = DIVIDE ( AVERAGE ( FactProducto[HorasAprobacionLaborables] ), 8 )
		formatString: 0.0
		lineageTag: 11111111-1111-4111-8111-111111111105

	measure 'Horas estimadas promedio' = AVERAGE ( FactProducto[HorasEstimadas] )
		formatString: 0.0
		lineageTag: 11111111-1111-4111-8111-111111111106

	measure 'Total aprobaciones' = COUNTROWS ( FactAprobacion )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222201

	measure 'Requerimientos abiertos' = CALCULATE ( [Total requerimientos], FactRequerimiento[EsFinalizado] = FALSE () )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222202

	measure 'Requerimientos completados' = CALCULATE ( [Total requerimientos], FactRequerimiento[EsCompletado] = TRUE () )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222203

	measure 'Requerimientos rechazados' = CALCULATE ( [Total requerimientos], FactRequerimiento[EsRechazado] = TRUE () )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222204

	measure 'Productos pendientes aprobacion' = CALCULATE ( [Total productos], FactProducto[EsPendienteAprobacion] = TRUE () )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222205

	measure 'Productos en correccion' = CALCULATE ( [Total productos], FactProducto[EsEnCorreccion] = TRUE () )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222206

	measure 'Productos en carga tecnica' = CALCULATE ( [Total productos], FactProducto[EsCargaTecnica] = TRUE () )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222207

	measure 'Aprobaciones rechazadas' = CALCULATE ( [Total aprobaciones], FactAprobacion[EsRechazado] = 1 )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222208

	measure 'Tasa aprobacion' = DIVIDE ( SUM ( FactAprobacion[EsAprobado] ), [Total aprobaciones] )
		formatString: 0.0%
		lineageTag: 22222222-2222-4222-8222-222222222209

	measure 'Total respuestas satisfaccion' = COUNTROWS ( FactSatisfaccion )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222210

	measure 'Calidad promedio' = AVERAGE ( FactSatisfaccion[Calidad] )
		formatString: 0.0
		lineageTag: 22222222-2222-4222-8222-222222222211

	measure 'Recomendacion promedio' = AVERAGE ( FactSatisfaccion[Recomienda] )
		formatString: 0.0
		lineageTag: 22222222-2222-4222-8222-222222222212

	measure 'Cumplimiento tiempo promedio' = AVERAGE ( FactSatisfaccion[CumplimientoTiempo] )
		formatString: 0.0
		lineageTag: 22222222-2222-4222-8222-222222222213


	measure 'Total usuarios' = COUNTROWS ( FactUsoUsuario )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222220

	measure 'Usuarios activos' = CALCULATE ( COUNTROWS ( FactUsoUsuario ), FactUsoUsuario[EsActivo] = TRUE () )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222214

	measure 'Usuarios ingreso ultimos 7 dias' = SUM ( FactUsoUsuario[IngresoUltimos7Dias] )
		formatString: 0
		lineageTag: 22222222-2222-4222-8222-222222222215

	measure 'Horas promedio desde ultimo ingreso' = AVERAGE ( FactUsoUsuario[HorasDesdeUltimoIngreso] )
		formatString: 0.0
		lineageTag: 22222222-2222-4222-8222-222222222216

	measure 'Tasa lectura notificaciones' = DIVIDE ( SUM ( FactUsoUsuario[NotificacionesLeidas] ), SUM ( FactUsoUsuario[NotificacionesRecibidas] ) )
		formatString: 0.0%
		lineageTag: 22222222-2222-4222-8222-222222222217

	measure 'Peso operativo total' = SUM ( FactProducto[PesoOperativo] )
		formatString: 0.0
		lineageTag: 22222222-2222-4222-8222-222222222218

	measure 'Horas estimadas total' = SUM ( FactProducto[HorasEstimadas] )
		formatString: 0.0
		lineageTag: 22222222-2222-4222-8222-222222222219

	column Key
		dataType: string
		isHidden
		lineageTag: 3a512df2-4ed8-403d-9916-28d27de6a0ef
		sourceColumn: Key

	partition _Medidas = m
		mode: import
		source =
				let
				    Source = #table(type table [Key = text], {{"Medidas"}})
				in
				    Source
