table _Medidas
    measure 'Total requerimientos' = COUNTROWS ( FactRequerimiento )
    measure 'Requerimientos activos' = CALCULATE ( [Total requerimientos], FactRequerimiento[EsFinalizado] = 0, FactRequerimiento[EsEliminado] = FALSE () )
    measure 'Requerimientos completados' = CALCULATE ( [Total requerimientos], FactRequerimiento[EsCompletado] = 1 )
    measure 'Requerimientos rechazados' = CALCULATE ( [Total requerimientos], FactRequerimiento[EsRechazado] = 1 )
    measure 'Total productos' = COUNTROWS ( FactProducto )
    measure 'Productos activos' = CALCULATE ( [Total productos], FactProducto[EsAprobado] = 0, FactProducto[EsEliminado] = FALSE () )
    measure 'Productos pendientes de iniciar' = CALCULATE ( [Total productos], FactProducto[EstadoCodigo] = "Todo", FactProducto[EsEliminado] = FALSE () )
    measure 'Productos en ejecucion' = CALCULATE ( [Total productos], FactProducto[EstadoCodigo] IN { "InProgress", "EvidenceAttached" }, FactProducto[EsEliminado] = FALSE () )
    measure 'Productos en correccion' = CALCULATE ( [Total productos], FactProducto[EsEnCorreccion] = 1, FactProducto[EsEliminado] = FALSE () )
    measure 'Productos pendientes de aprobacion' = CALCULATE ( [Total productos], FactProducto[EsPendienteAprobacion] = 1, FactProducto[EsEliminado] = FALSE () )
    measure 'Productos aprobados' = CALCULATE ( [Total productos], FactProducto[EsAprobado] = 1 )
    measure 'Productos rechazados' = CALCULATE ( COUNTROWS ( FactAprobacion ), FactAprobacion[EsRechazado] = 1 )
    measure 'Porcentaje de cierre' = DIVIDE ( [Requerimientos completados], [Total requerimientos] )
    measure 'Tiempo promedio tecnico horas' = AVERAGEX ( FILTER ( FactProducto, FactProducto[EstadoCodigo] = "Approved" || NOT ISBLANK ( FactProducto[FechaEnvioAprobacionUtc] ) ), FactProducto[HorasTecnicasLaborables] )
    measure 'Tiempo promedio aprobacion horas' = AVERAGEX ( FILTER ( FactProducto, FactProducto[EsPendienteAprobacion] = 1 || NOT ISBLANK ( FactProducto[FechaUltimaDecisionUtc] ) ), FactProducto[HorasAprobacionLaborables] )
    measure 'Tiempo promedio total cerrado horas' = AVERAGEX ( FILTER ( FactRequerimiento, FactRequerimiento[EsCompletado] = 1 || FactRequerimiento[EsRechazado] = 1 ), FactRequerimiento[HorasLaborablesCiclo] )
    measure 'Antiguedad requerimientos abiertos horas' = AVERAGEX ( FILTER ( FactRequerimiento, FactRequerimiento[EsFinalizado] = 0 && FactRequerimiento[EsEliminado] = FALSE () ), FactRequerimiento[HorasLaborablesAntiguedad] )
    measure 'Dias de anticipacion' = AVERAGE ( FactRequerimiento[DiasAnticipacion] )
    measure 'Carga ponderada' = SUMX ( FILTER ( FactProducto, FactProducto[EsEliminado] = FALSE () && FactProducto[EsAprobado] = 0 ), FactProducto[PesoOperativo] )
    measure 'Horas estimadas pendientes' = SUMX ( FILTER ( FactProducto, FactProducto[EsEliminado] = FALSE () && FactProducto[EsAprobado] = 0 ), FactProducto[HorasEstimadas] )
    measure 'Capacidad disponible horas' = CALCULATE ( DISTINCTCOUNT ( DimUsuario[UsuarioId] ), CONTAINSSTRING ( DimUsuario[Roles], "Tecnico" ), DimUsuario[EsActivo] = TRUE () ) * 9
    measure 'Porcentaje de ocupacion' = DIVIDE ( [Horas estimadas pendientes], [Capacidad disponible horas] )
    measure 'Capacidad versus demanda' = [Capacidad disponible horas] - [Horas estimadas pendientes]
    measure 'Numero de reprocesos' = CALCULATE ( COUNTROWS ( FactAprobacion ), FactAprobacion[EsRechazado] = 1 )
    measure 'Satisfaccion promedio' = AVERAGE ( FactSatisfaccion[SatisfaccionGeneral] )
    measure 'Tasa de respuesta encuesta' = DIVIDE ( DISTINCTCOUNT ( FactSatisfaccion[RequerimientoId] ), [Requerimientos completados] )
    measure 'Usuarios activos' = CALCULATE ( DISTINCTCOUNT ( DimUsuario[UsuarioId] ), DimUsuario[EsActivo] = TRUE () )
    measure 'Usuarios con ingreso ultimos 7 dias' = CALCULATE ( DISTINCTCOUNT ( FactUsoUsuario[UsuarioId] ), FactUsoUsuario[IngresoUltimos7Dias] = 1 )
