import type { Activity, AgendaItem, Requirement, WorkdayRange } from "../../agenda/models/agenda.models";
import type { CalendarMode } from "../models/calendar.models";

export function startOfDay(value: Date) { const date = new Date(value); date.setHours(0, 0, 0, 0); return date; }
export function addDays(value: Date, amount: number) { const date = new Date(value); date.setDate(date.getDate() + amount); return startOfDay(date); }
export function addMonths(value: Date, amount: number) { const date = new Date(value); date.setMonth(date.getMonth() + amount); return startOfDay(date); }
export function weekDays(value: Date, includeWeekend = true) { const day = startOfDay(value); const monday = addDays(day, -((day.getDay() + 6) % 7)); return Array.from({ length: includeWeekend ? 7 : 5 }, (_, index) => addDays(monday, index)); }
export function monthGrid(value: Date) { const first = new Date(value.getFullYear(), value.getMonth(), 1); const start = addDays(first, -((first.getDay() + 6) % 7)); return Array.from({ length: 42 }, (_, index) => addDays(start, index)); }
export function periodDays(value: Date, mode: CalendarMode, includeWeekend: boolean) { return mode === "month" ? monthGrid(value) : mode === "week" || mode === "list" ? weekDays(value, includeWeekend) : [startOfDay(value)]; }
export function moveCalendarPeriod(value: Date, mode: CalendarMode, direction: number) { return mode === "day" ? addDays(value, direction) : mode === "week" || mode === "list" ? addDays(value, direction * 7) : addMonths(value, direction); }
export function isSameDay(left: Date, right: Date) { return left.getFullYear() === right.getFullYear() && left.getMonth() === right.getMonth() && left.getDate() === right.getDate(); }
export function itemsForDay(items: AgendaItem[], day: Date) { return items.filter((item) => isSameDay(new Date(item.startAt), day)).sort((left, right) => new Date(left.startAt).getTime() - new Date(right.startAt).getTime()); }
export function isInPeriod(item: AgendaItem, days: Date[]) { return days.some((day) => isSameDay(new Date(item.startAt), day)); }
export function buildDayHours(range: WorkdayRange) { const start = Math.max(0, Math.min(23, range.startHour)); const end = Math.max(start + 1, Math.min(24, range.endHour)); return Array.from({ length: end - start + 1 }, (_, index) => start + index); }
export function filterCalendarItems(items: AgendaItem[], selectedTechnician: string, campus: string, status: string, search: string, activities: Map<string, Activity>, requirements: Map<string, Requirement>) { const query = search.trim().toLowerCase(); return items.filter((item) => !selectedTechnician || item.technicianEmail.toLowerCase() === selectedTechnician.toLowerCase()).filter((item) => !campus || requirements.get(item.requirementId)?.campus === campus).filter((item) => !status || activities.get(item.activityId)?.status === status).filter((item) => !query || [item.title, item.notes, item.productId, item.productType, item.technicianName, item.technicianEmail, activities.get(item.activityId)?.status ?? "", requirements.get(item.requirementId)?.campus ?? ""].some((value) => value.toLowerCase().includes(query))); }
export function uniqueOptions(values: string[]) { return Array.from(new Set(values.filter(Boolean))).sort((a, b) => a.localeCompare(b)); }
export function toDateInput(value: Date) { return new Date(value.getTime() - value.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); }
export function duration(item: AgendaItem) { return Math.max(0, (new Date(item.endAt).getTime() - new Date(item.startAt).getTime()) / 3_600_000); }
export function timeRange(item: AgendaItem) { const options: Intl.DateTimeFormatOptions = { hour: "2-digit", minute: "2-digit" }; return `${new Date(item.startAt).toLocaleTimeString("es-EC", options)} - ${new Date(item.endAt).toLocaleTimeString("es-EC", options)}`; }
export function periodLabel(value: Date, mode: CalendarMode, includeWeekend: boolean) { if (mode === "day") return value.toLocaleDateString("es-EC", { dateStyle: "full" }); if (mode === "week" || mode === "list") { const days = weekDays(value, includeWeekend); return `${shortDate(days[0])} - ${shortDate(days.at(-1) as Date)}`; } return value.toLocaleDateString("es-EC", { month: "long", year: "numeric" }); }
export function calendarSummary(items: AgendaItem[], mode: CalendarMode) { const label = mode === "day" ? "del día" : mode === "week" || mode === "list" ? "de la semana" : "del mes"; return `${items.length} bloques ${label}, ${items.reduce((sum, item) => sum + duration(item), 0).toFixed(1)} horas planificadas.`; }
export function shortDate(value: Date) { return value.toLocaleDateString("es-EC", { day: "2-digit", month: "short" }); }
export function calendarStatusLabel(status: string) { return ({ Todo: "Por hacer", InProgress: "Producto en proceso", EvidenceAttached: "Evidencia adjunta", PendingApproval: "Pendiente de aprobación", Approved: "Aprobado", Rejected: "Producto en proceso" } as Record<string, string>)[status] ?? status; }
