import type { Activity, AgendaItem, Requirement, Technician } from "../../agenda/models/agenda.models";
import { durationHours } from "../../agenda/utils/agenda.utils";
import { addDays, isInPeriod, startOfDay, weekDays } from "../../agenda-calendar/utils/calendar.utils";
import type { AgendaMetricsResult, MetricPeriod, WorkloadItem } from "../models/metrics.models";

export function metricPeriodDays(value: Date, period: MetricPeriod) { if (period === "day") return [startOfDay(value)]; if (period === "week") return weekDays(value, false); const end = new Date(value.getFullYear(), value.getMonth() + 1, 0); return Array.from({ length: end.getDate() }, (_, index) => startOfDay(new Date(value.getFullYear(), value.getMonth(), index + 1))); }
export function moveMetricPeriod(value: Date, period: MetricPeriod, direction: number) { if (period === "day") return addDays(value, direction); if (period === "week") return addDays(value, direction * 7); const result = new Date(value); result.setMonth(result.getMonth() + direction); return startOfDay(result); }
export function capacityByPeriod(period: MetricPeriod) { return period === "day" ? 8 : period === "month" ? 160 : 40; }
export function calculateCapacity(plannedHours: number, technicianCount: number, period: MetricPeriod) { const capacityHours = Math.max(1, Math.max(technicianCount, 1) * capacityByPeriod(period)); return { capacityHours, occupancy: Math.min(100, Math.round((Math.max(0, plannedHours) / capacityHours) * 100)), availability: Math.max(0, capacityHours - Math.max(0, plannedHours)) }; }
export function matchesMetricActivity(item: Activity, term: string, requirement?: Requirement) { const query = term.trim().toLowerCase(); return !query || [item.productId, item.productType, item.productResponsible, item.status, item.observations, requirement?.campus ?? "", requirement?.activityOrEvent ?? "", requirement?.code ?? ""].some((value) => value.toLowerCase().includes(query)); }
export function buildAgendaMetrics({ agendaItems, activities, requirements, technicians, period, cursorDate, selectedTechnician, selectedCampus, selectedStatus, search, now = new Date() }: { agendaItems: AgendaItem[]; activities: Activity[]; requirements: Requirement[]; technicians: Technician[]; period: MetricPeriod; cursorDate: Date; selectedTechnician: string; selectedCampus: string; selectedStatus: string; search: string; now?: Date }): AgendaMetricsResult {
  const requirementById = new Map(requirements.map((item) => [item.id, item])); const activityById = new Map(activities.map((item) => [item.id, item])); const days = metricPeriodDays(cursorDate, period);
  const items = agendaItems.filter((item) => !selectedTechnician || item.technicianEmail.toLowerCase() === selectedTechnician.toLowerCase()).filter((item) => !selectedCampus || requirementById.get(item.requirementId)?.campus === selectedCampus).filter((item) => !selectedStatus || activityById.get(item.activityId)?.status === selectedStatus).filter((item) => isInPeriod(item, days));
  const filteredActivities = activities.filter((item) => !selectedTechnician || item.productResponsible.toLowerCase() === selectedTechnician.toLowerCase()).filter((item) => !selectedCampus || requirementById.get(item.requirementId)?.campus === selectedCampus).filter((item) => !selectedStatus || item.status === selectedStatus).filter((item) => matchesMetricActivity(item, search, requirementById.get(item.requirementId)));
  const searchedItems = items.filter((item) => !search.trim() || matchesMetricActivity(activityById.get(item.activityId) ?? ({ productId: item.productId, productType: item.productType, productResponsible: item.technicianEmail, status: "", observations: "" } as Activity), search, requirementById.get(item.requirementId)));
  const scheduled = new Set(searchedItems.map((item) => item.activityId)); const plannedHours = searchedItems.reduce((sum, item) => sum + durationHours(item), 0); const capacity = calculateCapacity(plannedHours, selectedTechnician ? 1 : technicians.length, period);
  const open = filteredActivities.filter((item) => !["Approved", "Completed"].includes(item.status)); const pendingPlanning = open.filter((item) => !scheduled.has(item.id)).length; const riskLimit = addDays(now, 7).getTime(); const atRisk = open.filter((item) => item.productDeliveryDate && !scheduled.has(item.id) && new Date(item.productDeliveryDate).getTime() <= riskLimit).length;
  return { items: searchedItems, activities: filteredActivities, summary: { plannedHours, ...capacity, pendingPlanning, atRisk }, campusLoad: aggregate(searchedItems, (item) => requirementById.get(item.requirementId)?.campus || "Sin sede"), technicianLoad: aggregate(searchedItems, (item) => item.technicianName || item.technicianEmail), activityById, requirementById };
}
function aggregate(items: AgendaItem[], label: (item: AgendaItem) => string): WorkloadItem[] { const values = new Map<string, { blocks: number; hours: number }>(); for (const item of items) { const key = label(item); const current = values.get(key) ?? { blocks: 0, hours: 0 }; values.set(key, { blocks: current.blocks + 1, hours: current.hours + durationHours(item) }); } const max = Math.max(1, ...Array.from(values.values(), (item) => item.hours)); return Array.from(values, ([name, value]) => ({ label: name, ...value, percent: Math.round((value.hours / max) * 100) })).sort((a, b) => b.hours - a.hours); }
export function metricPeriodLabel(value: Date, period: MetricPeriod) { if (period === "day") return value.toLocaleDateString("es-EC", { dateStyle: "full" }); if (period === "week") { const days = weekDays(value, false); return `${days[0].toLocaleDateString("es-EC")} - ${days.at(-1)?.toLocaleDateString("es-EC")}`; } return value.toLocaleDateString("es-EC", { month: "long", year: "numeric" }); }
