import { describe, expect, it } from "vitest";
import { buildAgendaMetrics, calculateCapacity, capacityByPeriod, metricPeriodDays, metricPeriodLabel, moveMetricPeriod } from "./metrics.utils";
describe("agenda metrics", () => {
  it("calcula capacidad sin dividir por cero", () => { expect(capacityByPeriod("day")).toBe(8); expect(capacityByPeriod("week")).toBe(40); expect(capacityByPeriod("month")).toBe(160); expect(calculateCapacity(0, 0, "day")).toEqual({ capacityHours: 8, occupancy: 0, availability: 8 }); expect(calculateCapacity(20, 1, "day").occupancy).toBe(100); });
  it("construye periodos y navegación", () => { const date = new Date("2026-02-10T12:00:00"); expect(metricPeriodDays(date, "day")).toHaveLength(1); expect(metricPeriodDays(date, "week")).toHaveLength(5); expect(metricPeriodDays(date, "month")).toHaveLength(28); expect(moveMetricPeriod(date, "week", 1).getDate()).toBe(17); expect(moveMetricPeriod(date, "month", 1).getMonth()).toBe(2); expect(metricPeriodLabel(date, "week")).toContain("-"); });
  it("agrega horas, sedes, técnicos, pendientes y riesgo", () => { const result = buildAgendaMetrics({ agendaItems: [item()], activities: [activity(), activity({ id: "p2", productId: "P2", productDeliveryDate: "2026-02-12" })], requirements: [requirement()], technicians: [technician()], period: "month", cursorDate: new Date("2026-02-10"), selectedTechnician: "", selectedCampus: "", selectedStatus: "", search: "", now: new Date("2026-02-10") }); expect(result.summary.plannedHours).toBe(2); expect(result.summary.pendingPlanning).toBe(1); expect(result.summary.atRisk).toBe(1); expect(result.campusLoad[0]).toMatchObject({ label: "Centro", blocks: 1, hours: 2 }); expect(result.technicianLoad[0].percent).toBe(100); });
  it("filtra y tolera datos incompletos", () => { const result = buildAgendaMetrics({ agendaItems: [item({ technicianName: "", requirementId: "missing" })], activities: [activity()], requirements: [], technicians: [], period: "day", cursorDate: new Date("2026-02-10"), selectedTechnician: "otro", selectedCampus: "", selectedStatus: "", search: "x" }); expect(result.items).toEqual([]); expect(result.summary.plannedHours).toBe(0); expect(result.summary.availability).toBeGreaterThan(0); expect(result.campusLoad).toEqual([]); });
});
function activity(overrides: Record<string, unknown> = {}) { return { id: "p1", requirementId: "r1", productId: "P1", requirementTypeId: "r", requirementType: "R", strategicObjective: "O", targetAudienceId: "t", targetAudience: "T", productTypeId: "p", productType: "Video", diffusionChannelId: "d", diffusionChannel: "Web", mainKpiId: "k", mainKpi: "K", productResponsible: "tech@example.com", observations: "", status: "InProgress", statusId: "s", ...overrides } as never; }
function requirement() { return { id: "r1", code: "R", activityOrEvent: "Evento", requestedBy: "u", facultyId: "f", faculty: "F", career: "C", campusId: "c", campus: "Centro", place: "P", startDate: "2026-02-10", endDate: "2026-02-10", eventObjective: "O", eventFormatId: "e", eventFormat: "E", requestDate: "x", status: "InProgress", statusId: "s" }; }
function technician() { return { id: "t", name: "Tech", email: "tech@example.com", roles: ["Tecnico"], isActive: true }; }
function item(overrides: Record<string, unknown> = {}) { return { id: "a1", activityId: "p1", requirementId: "r1", productId: "P1", productType: "Video", technicianName: "Tech", technicianEmail: "tech@example.com", startAt: "2026-02-10T08:00:00", endAt: "2026-02-10T10:00:00", title: "Campaña", notes: "", ...overrides }; }
