"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { getSession, showToast } from "../../../app/lib";
import { getAgendaWorkspace } from "../../agenda/services/agenda.service";
import { buildWorkdayRange, filterAgendaActivities, filterAgendaTechnicians, mergeAgendaReservations } from "../../agenda/utils/agenda.utils";
import type { Technician } from "../../agenda/models/agenda.models";
import { startOfDay, uniqueOptions } from "../../agenda-calendar/utils/calendar.utils";
import type { MetricPeriod } from "../models/metrics.models";
import { buildAgendaMetrics, moveMetricPeriod } from "../utils/metrics.utils";

export function useAgendaMetrics() {
  const [data, setData] = useState<Awaited<ReturnType<typeof getAgendaWorkspace>> | null>(null); const [period, setPeriod] = useState<MetricPeriod>("week"); const [cursorDate, setCursorDate] = useState(() => startOfDay(new Date())); const [selectedTechnician, setSelectedTechnician] = useState(""); const [selectedCampus, setSelectedCampus] = useState(""); const [selectedStatus, setSelectedStatus] = useState(""); const [search, setSearch] = useState(""); const [isLoading, setIsLoading] = useState(true); const [isRefreshing, setIsRefreshing] = useState(false); const [loadError, setLoadError] = useState("");
  const load = useCallback((initial = false) => { const request = (async () => { initial ? setIsLoading(true) : setIsRefreshing(true); try { const next = await getAgendaWorkspace(); const session = getSession(); const technicians = filterAgendaTechnicians(next.technicians, session); const fallback: Technician[] = session ? [{ id: session.user.id, name: session.user.name, email: session.user.email, roles: session.user.roles, isActive: true }] : []; const visibleTechnicians = technicians.length ? technicians : fallback; const canSeeAll = Boolean(session?.user.roles.some((role) => ["Administrador", "Coordinador"].includes(role))); setData({ ...next, technicians: visibleTechnicians, activities: filterAgendaActivities(next.activities, session) }); setSelectedTechnician((value) => value || (canSeeAll ? "" : visibleTechnicians[0]?.email ?? "")); setLoadError(""); } catch (error) { const feedback = error instanceof Error ? error.message : "No se pudieron cargar métricas de agenda."; setLoadError(feedback); showToast(feedback, "error"); if (!getSession()) window.location.assign("/login"); throw error; } finally { setIsLoading(false); setIsRefreshing(false); } })(); return request; }, []);
  useEffect(() => { void load(true).catch(() => undefined); }, [load]);
  const metrics = useMemo(() => { if (!data) return null; const requirements = new Map(data.requirements.map((item) => [item.id, item])); const agenda = mergeAgendaReservations(data.items, data.activities, requirements, data.technicians, buildWorkdayRange(data.workdayStartTime, data.workdayEndTime)); return buildAgendaMetrics({ agendaItems: agenda, activities: data.activities, requirements: data.requirements, technicians: data.technicians, period, cursorDate, selectedTechnician, selectedCampus, selectedStatus, search }); }, [cursorDate, data, period, search, selectedCampus, selectedStatus, selectedTechnician]);
  return { metrics, technicians: data?.technicians ?? [], campuses: uniqueOptions(data?.requirements.map((item) => item.campus) ?? []), statuses: uniqueOptions(data?.activities.map((item) => item.status) ?? []), period, setPeriod, cursorDate, setCursorDate, movePeriod: (direction: number) => setCursorDate((value) => moveMetricPeriod(value, period, direction)), today: () => setCursorDate(startOfDay(new Date())), selectedTechnician, setSelectedTechnician, selectedCampus, setSelectedCampus, selectedStatus, setSelectedStatus, search, setSearch, isLoading, isRefreshing, loadError, refresh: () => load() };
}
