import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { getSession, showToast } from "../../../app/lib";
import { getAgendaWorkspace } from "../../agenda/services/agenda.service";
import { useAgendaMetrics } from "./useAgendaMetrics";
vi.mock("../../../app/lib", () => ({ getSession: vi.fn(), showToast: vi.fn() })); vi.mock("../../agenda/services/agenda.service", () => ({ getAgendaWorkspace: vi.fn() }));
const sessionMock = vi.mocked(getSession), workspaceMock = vi.mocked(getAgendaWorkspace);
beforeEach(() => { vi.clearAllMocks(); sessionMock.mockReturnValue(session(["Administrador"])); workspaceMock.mockResolvedValue(workspace()); });
describe("useAgendaMetrics", () => {
  it("carga y calcula indicadores", async () => { const { result, unmount } = renderHook(() => useAgendaMetrics()); await waitFor(() => expect(result.current.isLoading).toBe(false)); expect(result.current.metrics).not.toBeNull(); expect(result.current.technicians).toHaveLength(2); unmount(); });
  it("aplica filtros y cambia periodos", async () => { const { result, unmount } = renderHook(() => useAgendaMetrics()); await waitFor(() => expect(result.current.isLoading).toBe(false)); act(() => { result.current.setSelectedTechnician("tech@example.com"); result.current.setSelectedCampus("Centro"); result.current.setSelectedStatus("InProgress"); result.current.setSearch("P1"); result.current.setPeriod("month"); }); expect(result.current.metrics?.activities).toHaveLength(1); const before = result.current.cursorDate; act(() => result.current.movePeriod(1)); expect(result.current.cursorDate.getTime()).not.toBe(before.getTime()); act(() => result.current.today()); expect(result.current.cursorDate.getHours()).toBe(0); unmount(); });
  it("restringe técnicos por sesión", async () => { sessionMock.mockReturnValue(session(["Tecnico"])); const { result, unmount } = renderHook(() => useAgendaMetrics()); await waitFor(() => expect(result.current.isLoading).toBe(false)); expect(result.current.technicians).toHaveLength(1); expect(result.current.selectedTechnician).toBe("tech@example.com"); unmount(); });
  it("maneja error recuperable", async () => { workspaceMock.mockRejectedValueOnce(new Error("Sin conexión")); const { result, unmount } = renderHook(() => useAgendaMetrics()); await waitFor(() => expect(result.current.loadError).toBe("Sin conexión")); expect(showToast).toHaveBeenCalledWith("Sin conexión", "error"); await act(async () => { await result.current.refresh(); }); expect(result.current.loadError).toBe(""); unmount(); });
});
function session(roles: string[]) { return { accessToken: "t", expiresAt: "x", user: { id: "u", name: "Tech", email: "tech@example.com", roles, screenPermissions: ["agenda-metrics"] } }; }
function workspace() { return { activities: [{ id: "p1", requirementId: "r1", productId: "P1", requirementTypeId: "r", requirementType: "R", strategicObjective: "O", targetAudienceId: "t", targetAudience: "T", productTypeId: "p", productType: "Video", diffusionChannelId: "d", diffusionChannel: "Web", mainKpiId: "k", mainKpi: "K", productResponsible: "tech@example.com", observations: "", status: "InProgress", statusId: "s" }], requirements: [{ id: "r1", code: "R", activityOrEvent: "Evento", requestedBy: "u", facultyId: "f", faculty: "F", career: "C", campusId: "c", campus: "Centro", place: "P", startDate: "2026-01-01", endDate: "2026-12-31", eventObjective: "O", eventFormatId: "e", eventFormat: "E", requestDate: "x", status: "InProgress", statusId: "s" }], technicians: [{ id: "t", name: "Tech", email: "tech@example.com", roles: ["Tecnico"], isActive: true }, { id: "o", name: "Otro", email: "o@x", roles: ["Tecnico"], isActive: true }], items: [], workdayStartTime: "08:00", workdayEndTime: "17:00", replanningWindowDays: 3 }; }
