import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { getSession, showToast } from "../../../app/lib";
import { deleteAgendaItem, getAgendaWorkspace, saveAgendaItem } from "../services/agenda.service";
import { useAgendaWorkspace } from "./useAgendaWorkspace";
vi.mock("../../../app/lib", () => ({ getSession: vi.fn(), showToast: vi.fn() }));
vi.mock("../services/agenda.service", () => ({ deleteAgendaItem: vi.fn(), getAgendaWorkspace: vi.fn(), saveAgendaItem: vi.fn() }));
const sessionMock = vi.mocked(getSession), workspaceMock = vi.mocked(getAgendaWorkspace), saveMock = vi.mocked(saveAgendaItem), deleteMock = vi.mocked(deleteAgendaItem);
beforeEach(() => { vi.clearAllMocks(); sessionMock.mockReturnValue({ accessToken: "t", expiresAt: "x", user: { id: "u", name: "Tech", email: "tech@example.com", roles: ["Tecnico"], screenPermissions: ["agenda"] } }); workspaceMock.mockResolvedValue(workspace()); saveMock.mockResolvedValue({} as never); deleteMock.mockResolvedValue(undefined as never); vi.spyOn(window, "confirm").mockReturnValue(true); });
describe("useAgendaWorkspace", () => {
  it("carga permisos, reservas y métricas", async () => { const { result, unmount } = renderHook(() => useAgendaWorkspace()); await waitFor(() => expect(result.current.isLoading).toBe(false)); expect(result.current.technicians).toHaveLength(1); expect(result.current.items.length).toBeGreaterThan(0); expect(result.current.agendaHours).toBeGreaterThan(0); unmount(); });
  it("guarda alta y edición con bloqueo", async () => { let finish!: () => void; saveMock.mockReturnValueOnce(new Promise((resolve) => { finish = () => resolve({} as never); })); const { result, unmount } = renderHook(() => useAgendaWorkspace()); await waitFor(() => expect(result.current.isLoading).toBe(false)); const values = { technicianEmail: "tech@example.com", activityId: "p1", startAt: "2026-01-01T08:00", endAt: "2026-01-01T10:00", title: "", notes: "" }; let first!: Promise<boolean>; await act(async () => { first = result.current.save(null, values); expect(await result.current.save(null, values)).toBe(false); }); finish(); await act(async () => { expect(await first).toBe(true); }); expect(saveMock).toHaveBeenCalledWith(null, expect.objectContaining({ title: "PROD-1 - Video" })); unmount(); });
  it("elimina y reporta errores", async () => { const { result, unmount } = renderHook(() => useAgendaWorkspace()); await waitFor(() => expect(result.current.isLoading).toBe(false)); await act(async () => { expect(await result.current.remove("a1")).toBe(true); }); deleteMock.mockRejectedValueOnce(new Error("Bloqueado")); await act(async () => { expect(await result.current.remove("a1")).toBe(false); }); expect(result.current.message).toBe("Bloqueado"); expect(showToast).toHaveBeenCalledWith("Bloqueado", "error"); unmount(); });
  it("expone error de carga y permite reintentar", async () => { workspaceMock.mockRejectedValueOnce(new Error("Sin conexión")); const { result, unmount } = renderHook(() => useAgendaWorkspace()); await waitFor(() => expect(result.current.loadError).toBe("Sin conexión")); await act(async () => { await result.current.refresh(); }); expect(result.current.loadError).toBe(""); unmount(); });
  it("edita, valida referencias y permite cancelar eliminación", async () => { const { result, unmount } = renderHook(() => useAgendaWorkspace()); await waitFor(() => expect(result.current.isLoading).toBe(false)); const values = { technicianEmail: "tech@example.com", activityId: "p1", startAt: "2026-01-01T08:00", endAt: "2026-01-01T10:00", title: "Editado", notes: "" }; await act(async () => { expect(await result.current.save({ id: "a1" } as never, values)).toBe(true); }); expect(result.current.message).toBe("Agenda actualizada correctamente."); await act(async () => { expect(await result.current.save(null, { ...values, activityId: "missing" })).toBe(false); }); vi.mocked(window.confirm).mockReturnValueOnce(false); await act(async () => { expect(await result.current.remove("a1")).toBe(false); }); unmount(); });
  it("usa feedback genérico en fallos sin Error", async () => { saveMock.mockRejectedValueOnce("fallo"); const { result, unmount } = renderHook(() => useAgendaWorkspace()); await waitFor(() => expect(result.current.isLoading).toBe(false)); await act(async () => { expect(await result.current.save(null, { technicianEmail: "tech@example.com", activityId: "p1", startAt: "2026-01-01T08:00", endAt: "2026-01-01T10:00", title: "", notes: "" })).toBe(false); }); expect(result.current.message).toBe("No se pudo guardar la agenda."); unmount(); });
});
function workspace() { return { activities: [{ id: "p1", requirementId: "r1", productId: "PROD-1", requirementTypeId: "r", requirementType: "R", strategicObjective: "O", targetAudienceId: "t", targetAudience: "T", productTypeId: "p", productType: "Video", diffusionChannelId: "d", diffusionChannel: "Web", mainKpiId: "k", mainKpi: "K", productResponsible: "tech@example.com", observations: "", status: "InProgress", statusId: "s" }], requirements: [{ id: "r1", code: "R", activityOrEvent: "E", requestedBy: "u", facultyId: "f", faculty: "F", career: "C", campusId: "c", campus: "C", place: "P", startDate: "2026-01-01", endDate: "2026-01-01", eventObjective: "O", eventFormatId: "e", eventFormat: "E", requestDate: "x", status: "InProgress", statusId: "s" }], technicians: [{ id: "t", name: "Tech", email: "tech@example.com", roles: ["Tecnico"], isActive: true }], items: [], workdayStartTime: "08:00", workdayEndTime: "17:00", replanningWindowDays: 3 }; }
