"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { getSession, showToast } from "../../../app/lib";
import type { AgendaFormValues } from "../schemas/agenda.schema";
import type { AgendaItem, Technician } from "../models/agenda.models";
import { deleteAgendaItem, getAgendaWorkspace, saveAgendaItem } from "../services/agenda.service";
import { buildWorkdayRange, durationHours, filterAgendaActivities, filterAgendaTechnicians, matchesAgenda, mergeAgendaReservations } from "../utils/agenda.utils";

export function useAgendaWorkspace() {
  const [data, setData] = useState<Awaited<ReturnType<typeof getAgendaWorkspace>> | null>(null);
  const [selectedTechnician, setSelectedTechnician] = useState(""); const [search, setSearch] = useState("");
  const [isLoading, setIsLoading] = useState(true); const [isRefreshing, setIsRefreshing] = useState(false); const [loadError, setLoadError] = useState(""); const [message, setMessage] = useState("");
  const pendingRef = useRef(new Set<string>()); const [pendingIds, setPendingIds] = useState<Set<string>>(() => new Set());
  const load = useCallback((initial = false) => {
    const request = (async () => { initial ? setIsLoading(true) : setIsRefreshing(true); try { const next = await getAgendaWorkspace(); const session = getSession(); const technicians = filterAgendaTechnicians(next.technicians, session); const fallback: Technician[] = session ? [{ id: session.user.id, name: session.user.name, email: session.user.email, roles: session.user.roles, isActive: true }] : []; const visibleTechnicians = technicians.length ? technicians : fallback; setData({ ...next, technicians: visibleTechnicians, activities: filterAgendaActivities(next.activities, session) }); setSelectedTechnician((value) => value || visibleTechnicians[0]?.email || ""); setLoadError(""); } catch (error) { const feedback = error instanceof Error ? error.message : "No se pudo cargar la agenda."; setLoadError(feedback); showToast(feedback, "error"); if (!getSession()) window.location.assign("/login"); throw error; } finally { setIsLoading(false); setIsRefreshing(false); } })();
    return request;
  }, []);
  const save = useCallback(async (item: AgendaItem | null, values: AgendaFormValues) => { const key = item?.id ?? "new"; if (pendingRef.current.has(key) || !data) return false; const activity = data.activities.find((value) => value.id === values.activityId); const technician = data.technicians.find((value) => value.email === values.technicianEmail); if (!activity || !technician) return false; pendingRef.current.add(key); setPendingIds(new Set(pendingRef.current)); try { await saveAgendaItem(item, { activityId: activity.id, technicianName: technician.name, technicianEmail: technician.email, startAt: new Date(values.startAt).toISOString(), endAt: new Date(values.endAt).toISOString(), title: values.title || `${activity.productId} - ${activity.productType}`, notes: values.notes, createdBy: getSession()?.user.email ?? "Sistema" }); const feedback = item ? "Agenda actualizada correctamente." : "Bloque de agenda creado correctamente."; setMessage(feedback); showToast(feedback); await load(); return true; } catch (error) { const feedback = error instanceof Error ? error.message : "No se pudo guardar la agenda."; setMessage(feedback); showToast(feedback, "error"); return false; } finally { pendingRef.current.delete(key); setPendingIds(new Set(pendingRef.current)); } }, [data, load]);
  const remove = useCallback(async (id: string) => { if (pendingRef.current.has(id) || !window.confirm("¿Eliminar este bloque de agenda?")) return false; pendingRef.current.add(id); setPendingIds(new Set(pendingRef.current)); try { await deleteAgendaItem(id); setMessage("Bloque eliminado correctamente."); showToast("Bloque eliminado correctamente."); await load(); return true; } catch (error) { const feedback = error instanceof Error ? error.message : "No se pudo eliminar el bloque."; setMessage(feedback); showToast(feedback, "error"); return false; } finally { pendingRef.current.delete(id); setPendingIds(new Set(pendingRef.current)); } }, [load]);
  useEffect(() => { void load(true).catch(() => undefined); }, [load]);
  const computed = useMemo(() => { if (!data) return { items: [], assigned: 0, hours: 0 }; const requirements = new Map(data.requirements.map((item) => [item.id, item])); const range = buildWorkdayRange(data.workdayStartTime, data.workdayEndTime); const all = mergeAgendaReservations(data.items, data.activities, requirements, data.technicians, range); const items = all.filter((item) => !selectedTechnician || item.technicianEmail.toLowerCase() === selectedTechnician.toLowerCase()).filter((item) => matchesAgenda(item, search)); return { items, assigned: data.activities.filter((item) => !selectedTechnician || item.productResponsible.toLowerCase() === selectedTechnician.toLowerCase()).length, hours: items.reduce((sum, item) => sum + durationHours(item), 0) }; }, [data, search, selectedTechnician]);
  return { activities: data?.activities ?? [], technicians: data?.technicians ?? [], items: computed.items, assignedProducts: computed.assigned, agendaHours: computed.hours, selectedTechnician, setSelectedTechnician, search, setSearch, isLoading, isRefreshing, loadError, message, pendingIds, refresh: () => load(), save, remove };
}
