"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { Save, X } from "lucide-react";
import { useForm } from "react-hook-form";
import { AccessibleDialog } from "../../../shared/components/AccessibleDialog";
import type { Activity, AgendaItem, Technician } from "../models/agenda.models";
import { agendaSchema, type AgendaFormValues } from "../schemas/agenda.schema";
import { toDateTimeInput } from "../utils/agenda.utils";
import styles from "../styles/Agenda.module.css";

export function AgendaForm({ item, activities, technicians, selectedTechnician, pending, onSave, onClose }: { item: AgendaItem | null; activities: Activity[]; technicians: Technician[]; selectedTechnician: string; pending: boolean; onSave: (item: AgendaItem | null, values: AgendaFormValues) => Promise<boolean>; onClose: () => void }) {
  const { register, handleSubmit, formState: { errors } } = useForm<AgendaFormValues>({ resolver: zodResolver(agendaSchema), defaultValues: { technicianEmail: item?.technicianEmail ?? selectedTechnician, activityId: item?.activityId ?? "", startAt: toDateTimeInput(item?.startAt), endAt: toDateTimeInput(item?.endAt), title: item?.title ?? "", notes: item?.notes ?? "" } });
  async function submit(values: AgendaFormValues) { if (await onSave(item, values)) onClose(); }
  return <AccessibleDialog labelledBy="agenda-form-title" onClose={onClose} closeDisabled={pending} backdropClassName={styles.dialogBackdrop} panelClassName={styles.dialogPanel}><div className="card-head"><div><h2 id="agenda-form-title">{item ? "Editar agenda" : "Nuevo bloque de agenda"}</h2><p>Relaciona el tiempo con un producto asignado.</p></div><button autoFocus className="icon-button" type="button" aria-label="Cerrar agenda" disabled={pending} onClick={onClose}><X size={16} /></button></div><form className="form top-space" onSubmit={handleSubmit(submit)} noValidate><Field label="Técnico" error={errors.technicianEmail?.message}><select {...register("technicianEmail")} disabled={pending}>{technicians.map((value) => <option key={value.id} value={value.email}>{value.name} - {value.email}</option>)}</select></Field><Field label="Producto" error={errors.activityId?.message}><select {...register("activityId")} disabled={pending}><option value="">Seleccione...</option>{activities.map((value) => <option key={value.id} value={value.id}>{value.productId} - {value.productType}</option>)}</select></Field><Field label="Inicio" error={errors.startAt?.message}><input type="datetime-local" {...register("startAt")} disabled={pending} /></Field><Field label="Fin" error={errors.endAt?.message}><input type="datetime-local" {...register("endAt")} disabled={pending} /></Field><Field label="Título" error={errors.title?.message} wide><input {...register("title")} disabled={pending} /></Field><Field label="Notas" error={errors.notes?.message} wide><textarea {...register("notes")} disabled={pending} /></Field><div className="form-actions"><button className="button" disabled={pending}><Save size={16} /> {pending ? "Guardando" : "Guardar"}</button><button className="button secondary" type="button" disabled={pending} onClick={onClose}><X size={16} /> Cancelar</button></div></form></AccessibleDialog>;
}
function Field({ label, error, wide = false, children }: { label: string; error?: string; wide?: boolean; children: React.ReactNode }) { return <label className={`field${wide ? " field-wide" : ""}`}><span>{label}</span>{children}{error && <small role="alert">{error}</small>}</label>; }
