"use client";
import { useCallback, useEffect, useRef, useState } from "react"; import { getSession, showToast } from "../../../app/lib"; import type { ManagedUser, SaveUserPayload } from "../models/user.models"; import { disableUser, getUsersWorkspace, saveUser } from "../services/user.service";
export function useUsersAdministration(pollInterval=10_000){const[users,setUsers]=useState<ManagedUser[]>([]),[roles,setRoles]=useState<string[]>([]),[screens,setScreens]=useState<string[]>([]),[message,setMessage]=useState("Usuarios y perfiles."),[isLoading,setIsLoading]=useState(true),[isRefreshing,setIsRefreshing]=useState(false),[loadError,setLoadError]=useState(""),[pendingIds,setPendingIds]=useState<Set<string>>(new Set());const active=useRef<Promise<void>|null>(null),pending=useRef(new Set<string>());
const load=useCallback((initial=false)=>{if(active.current)return active.current;const request=(async()=>{initial?setIsLoading(true):setIsRefreshing(true);try{const data=await getUsersWorkspace();setUsers(data.users);setRoles(data.roles);setScreens(data.screens);setLoadError("");}catch(error){const feedback=error instanceof Error?error.message:"No se pudieron cargar los usuarios.";setLoadError(feedback);if(initial)showToast(feedback,"error");if(!getSession())window.location.assign("/login");throw error;}finally{setIsLoading(false);setIsRefreshing(false);}})();active.current=request;void request.finally(()=>{if(active.current===request)active.current=null;}).catch(()=>undefined);return request;},[]);
useEffect(()=>{void load(true).catch(()=>undefined);const timer=window.setInterval(()=>void load(false).catch(()=>undefined),pollInterval);return()=>window.clearInterval(timer);},[load,pollInterval]);
const save=useCallback(async(user:ManagedUser|null,payload:SaveUserPayload)=>{try{await saveUser(user,payload);setMessage(user?"Usuario editado.":"Usuario creado.");showToast(user?"Usuario editado correctamente.":"Usuario creado correctamente.");await load(false);}catch(error){showToast(error instanceof Error?error.message:"No se pudo guardar el usuario.","error");throw error;}},[load]);
const disable=useCallback(async(id:string)=>{if(pending.current.has(id)||!window.confirm("¿Eliminar lógicamente este usuario? El usuario quedará inactivo."))return false;pending.current.add(id);setPendingIds(new Set(pending.current));try{await disableUser(id);showToast("Usuario eliminado lógicamente.");await load(false);return true;}catch(error){showToast(error instanceof Error?error.message:"No se pudo inactivar el usuario.","error");return false;}finally{pending.current.delete(id);setPendingIds(new Set(pending.current));}},[load]);
return{users,roles,screens,message,isLoading,isRefreshing,loadError,pendingIds,refresh:()=>load(false),save,disable};}
export type UsersAdministrationWorkspace=ReturnType<typeof useUsersAdministration>;
